from app.config import settings

print("CHATBOT_LLM_PROVIDER:", settings.CHATBOT_LLM_PROVIDER)
print("CHATBOT_OLLAMA_BASE_URL:", settings.CHATBOT_OLLAMA_BASE_URL)
print("CHATBOT_OLLAMA_MODEL:", settings.CHATBOT_OLLAMA_MODEL)
print("CHATBOT_LLM_TIMEOUT_SECONDS:", settings.CHATBOT_LLM_TIMEOUT_SECONDS)
